version: 2.1
jobs:
  #build:
    #...
  deployProduction:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "83:0f:18:9c:2d:44:b3:6b:5b:22:4c:6d:96:93:76:7a"
            - "a8:cc:0f:95:0a:96:72:e0:88:a1:ee:17:59:95:7a:3b"
      - run:
          name: Deploy Over SSH 
          command: |
             ssh servidores@13.66.4.189 "cd CircleCI-NodeApp && git pull && npm run deploy"
      - run:
          name: Deploy Over SSH 2
          command: |
             ssh nfs@52.171.197.75 "cd CircleCI-NodeApp && git pull && npm run deploy"

  deployDevelop:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a0:94:9d:80:1f:8f:20:f0:f6:dc:14:65:40:09:89:70"
      - run:
          name: Deploy Over SSH
          command: |
             ssh servidord@40.124.33.128 "cd CircleCI-NodeApp && git pull && npm run deploy"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      #- build
      - deployProduction:
          #requires:
          #  - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch
      - deployDevelop:
          #requires:
          #  - build # only deploy once build job has completed
          filters:
            branches:
              only: develop # only deploy on the develop branch


 
          
