 version: 2

 jobs:
   
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh servidordesarrollo@70.37.102.226

 
          
